// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCskynhJaZsJIreOpJgZfFXeUXQs_dkT7M',
    appId: '1:662275440520:web:078fcfdfc0d900ec26c43d',
    messagingSenderId: '662275440520',
    projectId: 'app-gastosv1',
    authDomain: 'app-gastosv1.firebaseapp.com',
    storageBucket: 'app-gastosv1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzd5ZaqJKhPFMJs488LNLoU3ND6JrgO6E',
    appId: '1:662275440520:android:d2971d6e5f207c2826c43d',
    messagingSenderId: '662275440520',
    projectId: 'app-gastosv1',
    storageBucket: 'app-gastosv1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3gz8KatD4jYd-ZIfsqcDQPfIOWkcclA0',
    appId: '1:662275440520:ios:6ca824dcf6fa44cb26c43d',
    messagingSenderId: '662275440520',
    projectId: 'app-gastosv1',
    storageBucket: 'app-gastosv1.firebasestorage.app',
    iosBundleId: 'com.example.appGastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3gz8KatD4jYd-ZIfsqcDQPfIOWkcclA0',
    appId: '1:662275440520:ios:6ca824dcf6fa44cb26c43d',
    messagingSenderId: '662275440520',
    projectId: 'app-gastosv1',
    storageBucket: 'app-gastosv1.firebasestorage.app',
    iosBundleId: 'com.example.appGastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCskynhJaZsJIreOpJgZfFXeUXQs_dkT7M',
    appId: '1:662275440520:web:86446f26f30c5df026c43d',
    messagingSenderId: '662275440520',
    projectId: 'app-gastosv1',
    authDomain: 'app-gastosv1.firebaseapp.com',
    storageBucket: 'app-gastosv1.firebasestorage.app',
  );

}